In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk','the glass of juice',
        'the cup of tea','I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',] 

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocabulary size
voc_size = 10000

## One hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5233, 3768, 3850, 4363],
 [5233, 3768, 3850, 649],
 [5233, 8808, 3850, 5750],
 [4887, 1691, 6490, 4402, 4340],
 [4887, 1691, 6490, 4402, 2310],
 [9807, 5233, 7148, 3850, 915],
 [3402, 8280, 9203, 4402]]

In [5]:
 ## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
sent_length = 8
embdded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen=sent_length)
print(embdded_docs)

[[   0    0    0    0 5233 3768 3850 4363]
 [   0    0    0    0 5233 3768 3850  649]
 [   0    0    0    0 5233 8808 3850 5750]
 [   0    0    0 4887 1691 6490 4402 4340]
 [   0    0    0 4887 1691 6490 4402 2310]
 [   0    0    0 9807 5233 7148 3850  915]
 [   0    0    0    0 3402 8280 9203 4402]]


In [7]:
## feature representation
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')
model.summary()

d:\Projects\GenAI_langchain_project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.predict(embdded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[-0.00908614,  0.01845311,  0.00704577, -0.03622914,
          0.0263538 ,  0.00940241,  0.0309921 ,  0.02422993,
         -0.03071716, -0.00476361],
        [-0.00908614,  0.01845311,  0.00704577, -0.03622914,
          0.0263538 ,  0.00940241,  0.0309921 ,  0.02422993,
         -0.03071716, -0.00476361],
        [-0.00908614,  0.01845311,  0.00704577, -0.03622914,
          0.0263538 ,  0.00940241,  0.0309921 ,  0.02422993,
         -0.03071716, -0.00476361],
        [-0.00908614,  0.01845311,  0.00704577, -0.03622914,
          0.0263538 ,  0.00940241,  0.0309921 ,  0.02422993,
         -0.03071716, -0.00476361],
        [ 0.02452544, -0.03538563, -0.01185973, -0.04600445,
          0.04253972,  0.02025947, -0.03332265, -0.019797  ,
         -0.01939756, -0.03632005],
        [ 0.01119778, -0.00718655,  0.02303317, -0.01181231,
          0.016495  , -0.00117475,  0.01463237,  0.03238894,
          0.03814072,  0.01055793],
        [ 0.02806573, -0.01172321,  0.04794777,  0.0

In [9]:
model.predict(embdded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [9]:
embdded_docs[0]

array([   0,    0,    0,    0,  679, 5533, 9155, 1973])

In [11]:
import numpy as np
output = model.predict(np.expand_dims(embdded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [12]:
output.shape

(1, 8, 10)

In [15]:
output[0]

array([[-0.00908614,  0.01845311,  0.00704577, -0.03622914,  0.0263538 ,
         0.00940241,  0.0309921 ,  0.02422993, -0.03071716, -0.00476361],
       [-0.00908614,  0.01845311,  0.00704577, -0.03622914,  0.0263538 ,
         0.00940241,  0.0309921 ,  0.02422993, -0.03071716, -0.00476361],
       [-0.00908614,  0.01845311,  0.00704577, -0.03622914,  0.0263538 ,
         0.00940241,  0.0309921 ,  0.02422993, -0.03071716, -0.00476361],
       [-0.00908614,  0.01845311,  0.00704577, -0.03622914,  0.0263538 ,
         0.00940241,  0.0309921 ,  0.02422993, -0.03071716, -0.00476361],
       [ 0.02452544, -0.03538563, -0.01185973, -0.04600445,  0.04253972,
         0.02025947, -0.03332265, -0.019797  , -0.01939756, -0.03632005],
       [ 0.01119778, -0.00718655,  0.02303317, -0.01181231,  0.016495  ,
        -0.00117475,  0.01463237,  0.03238894,  0.03814072,  0.01055793],
       [ 0.02806573, -0.01172321,  0.04794777,  0.03338033, -0.03191704,
         0.04080233, -0.04172073,  0.00280583